### ISSUE TITLE
Add support for Dependabot

### ISSUE THREAD

**Issue by hectcastro** [azavea/raster-vision#1075]
Comb repository for dependencies that we would want to manage via Dependabot and add support through `dependabot.yml`. Support for GitHub Security dependency updates have already been [enabled](https://github.com/azavea/raster-vision/settings/security_analysis) for this repository.

See:

- Simple: https://github.com/azavea/operations/blob/main/.github/dependabot.yml

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/gh_2fa_stats"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

- Smarter: https://github.com/raster-foundry/groundwork/blob/develop/.github/dependabot.yml

```yaml
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "."
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "polygon-clipping"
      - dependency-name: "deck.gl"
      - dependency-name: "@nebula.gl/layers"
      - dependency-name: "@nebula.gl/overlays"
      - dependency-name: "@types/mapbox-gl"
      - dependency-name: "mapbox-gl"
      - dependency-name: "@turf/bbox"
      - dependency-name: "@turf/bbox-polygon"
      - dependency-name: "@turf/boolean-contains"
      - dependency-name: "@turf/boolean-point-in-polygon"
      - dependency-name: "@turf/buffer"
      - dependency-name: "@turf/center"
      - dependency-name: "@turf/difference"
      - dependency-name: "@turf/helpers"
      - dependency-name: "@turf/intersect"
      - dependency-name: "@turf/simplify"
```

- https://github.com/raster-foundry/groundwork/blob/develop/.github/workflows/merge-dependabot.yml

```yaml
name: merge-dependabot

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v1.8.79
        with:
          GITHUB_LOGIN: "dependabot[bot]"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
```
